---
:local_server:
    storage_directory: "/media/APTrust/"
    storage_root: "/media/APTrust/"
    fits_location: "bag"
    ignore: ".DS_Store"
:institution:
    source_org: "University of Miami"
    institution: "miami.edu"
:remote:
    user: ""
    password: ""
    includes: ""
:aws:
    url: ""
    access_id: ""
    secret_key: ""
    bucket_name: ""
    region: ""
